language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run client:init
  
before_script:
  - npm run client:build

script:
  - npm run test:coverage && npm run test:client:coverage

on:
  branch: master

